/**
 * Self-host the site's fonts.
 *
 * Fetches Google Fonts' CSS for the four families, keeps only the subsets the
 * page uses (Latin, Latin Extended, and Ethiopic for the Ge'ez numerals),
 * downloads those WOFF2 files into public/fonts/ and writes
 * src/styles/fonts.css pointing at them.
 *
 * Why: no request to a third party on any page view (the privacy notice
 * depends on it), two fewer origins to connect to on a slow mobile link, and
 * a Content-Security-Policy that no longer needs to allow Google.
 *
 * Usage: npm run fonts   (only needed when the families or weights change)
 */
import { writeFile, mkdir } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,400;1,9..144,600' +
  '&family=Archivo:wght@400;500;600;700' +
  '&family=Fira+Code:wght@400;500' +
  '&family=Noto+Serif+Ethiopic:wght@400;500' +
  '&display=swap';
const KEEP = new Set(['latin', 'latin-ext', 'ethiopic']);
// A current browser UA, so Google serves WOFF2 with unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];

await mkdir('public/fonts', { recursive: true });
const saved = new Map();
const out = [];

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const style = /font-style: (\w+)/.exec(block)[1];
  const url = /url\((https:[^)]+)\)/.exec(block)[1];
  // Variable families serve one file for several weights; download it once.
  if (!saved.has(url)) {
    const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}-${style}-${saved.size}.woff2`;
    const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(`public/fonts/${name}`, bytes);
    saved.set(url, { name, size: bytes.length });
  }
  out.push(`/* ${subset} */\n${block.replace(url, `/fonts/${saved.get(url).name}`)}`);
}

await writeFile(
  'src/styles/fonts.css',
  `/* Self-hosted fonts — generated by scripts/fonts.mjs. Do not edit by hand. */\n\n${out.join('\n\n')}\n`
);

let total = 0;
for (const { name, size } of saved.values()) {
  total += size;
  console.log(`  ${name}  ${(size / 1024).toFixed(1)} kB`);
}
console.log(`${saved.size} files, ${(total / 1024).toFixed(1)} kB total`);
